'''
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal
numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48,
is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are
pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
'''


def pent(n):
    return n * (3 * n - 1) / 2


pent_nums = {pent(n) for n in range(1, 10000)}

for t1 in pent_nums:
    for t2 in pent_nums:
        if t1 == t2:
            continue

        sm = t1 + t2
        df = abs(t1 - t2)
        if sm in pent_nums and df in pent_nums:
            print t1, t2, sm, df
