"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

def pentagonal(n):
    return n * (3 * n - 1) / 2

pents = {}
n = 5000
for i in range(1, n):
    pents[pentagonal(i)] = i #poor man's hash map?

distance = 1000000000000
for j in pents:
    for k in pents:
        if (j + k) in pents and (j - k) in pents:
            d = abs(j - k)
            if d < distance:
                distance = d
print(distance)
        

