"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def triangle(n):
    return int(n * (n + 1) / 2)

def pentagonal(n):
    return int(n * (3 * n - 1) / 2)

def hexagonal(n):
    return int(n * (2 * n - 1))

n = 500000
T = set()
P = set()
H = set()
for i in range(1, n):
    #sets make more sense than dictionaries for determining if a number is a member of both sets
    #and maintains the hash table speed lookups 
    T.add(triangle(i))
    P.add(pentagonal(i))
    H.add(hexagonal(i))

for term in T:
    if term in P and term in H:
        print(term)
